# Generated by Django 2.0.1 on 2018-01-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20180103_1432'),
        ('users', '0002_auto_20180102_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reading_list',
            field=models.ManyToManyField(to='publications.Article'),
        ),
    ]
